from django.core.management.base import BaseCommand
from movies.models import Movie

MOVIES_100 = [
    # -------------------------------------------------------------
    # KOLLYWOOD / TAMIL BLOCKBUSTERS & RECENT HITS (1 to 60)
    # -------------------------------------------------------------
    {
        "title": "Coolie",
        "release_year": 2025,
        "genre": "Action",
        "director": "Lokesh Kanagaraj",
        "synopsis": "An enigmatic and stylish harbor worker with a fierce past unravels a high-stakes gold smuggling syndicate operated across international waters.",
        "poster_url": "https://image.tmdb.org/t/p/w500/z0T0KzP8s14HkJrXoXwYdE9eR4m.jpg",
    },
    {
        "title": "Thug Life",
        "release_year": 2025,
        "genre": "Action Crime",
        "director": "Mani Ratnam",
        "synopsis": "Rangaraya Sakthivel Nayakar, a revered gangster and Yakuza affiliate, navigates clan warfare, legacy betrayals, and redemption across eras.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1hK5v32cW2q3NqJ9wK5kX7M5kC1.jpg",
    },
    {
        "title": "The Greatest of All Time (GOAT)",
        "release_year": 2024,
        "genre": "Sci-Fi Action",
        "director": "Venkat Prabhu",
        "synopsis": "An elite anti-terrorist agent confronts a catastrophic threat when his cloned younger self resurfaces seeking retribution for a buried mission.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hhVwK9E6hN6Z9J7bX2M5tQ1rY8e.jpg",
    },
    {
        "title": "Vettaiyan",
        "release_year": 2024,
        "genre": "Action Drama",
        "director": "T. J. Gnanavel",
        "synopsis": "An uncompromising encounter specialist cop faces deep moral and legal dilemmas while investigating a tragic educator's murder linked to systemic corruption.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7V9N2s8mX4M5kQ1rY8eZ2bK6wT5.jpg",
    },
    {
        "title": "Leo",
        "release_year": 2023,
        "genre": "Action",
        "director": "Lokesh Kanagaraj",
        "synopsis": "Parthiban is a mild-mannered cafe owner in Kashmir who fends off violent thugs, only to find a ruthless crime syndicate claiming he is their long-lost heir.",
        "poster_url": "https://upload.wikimedia.org/wikipedia/en/7/75/Leo_%282023_Indian_film%29.jpg",
    },
    {
        "title": "Jailer",
        "release_year": 2023,
        "genre": "Action Drama",
        "director": "Nelson Dilipkumar",
        "synopsis": "A retired prison warden steps out of retirement and taps into his lethal past connections to avenge the apparent killing of his police officer son.",
        "poster_url": "https://image.tmdb.org/t/p/w500/q22rZq4Z4M8P0eG8q8E6K5tQ1rY.jpg",
    },
    {
        "title": "Vikram",
        "release_year": 2022,
        "genre": "Action Thriller",
        "director": "Lokesh Kanagaraj",
        "synopsis": "A covert black-ops veteran leads a squad of vigilantes to wage war against a ruthless drug lord and his syndicate across the streets of Chennai.",
        "poster_url": "https://upload.wikimedia.org/wikipedia/en/9/93/Vikram_2022_poster.jpg",
    },
    {
        "title": "Amaran",
        "release_year": 2024,
        "genre": "Biographical Action",
        "director": "Rajkumar Periasamy",
        "synopsis": "The inspiring real-life journey and ultimate sacrifice of Major Mukund Varadarajan of the Rashtriya Rifles during counter-insurgency operations in Kashmir.",
        "poster_url": "https://image.tmdb.org/t/p/w500/w7k6g8M3p5rQ9vL2nZ8tK1rY4eM.jpg",
    },
    {
        "title": "Maharaja",
        "release_year": 2024,
        "genre": "Action Thriller",
        "director": "Nithilan Saminathan",
        "synopsis": "A quiet barber files a baffling police complaint about a stolen dustbin, masking a devastating mission for justice and revenge.",
        "poster_url": "https://image.tmdb.org/t/p/w500/jL5cW8mX4M5kQ1rY8eZ2bK6wT5v.jpg",
    },
    {
        "title": "Raayan",
        "release_year": 2024,
        "genre": "Action Crime",
        "director": "Dhanush",
        "synopsis": "A protective elder brother operating a fast-food stall in north Madras is pulled into a lethal gang war to protect his siblings.",
        "poster_url": "https://image.tmdb.org/t/p/w500/a3K5v32cW2q3NqJ9wK5kX7M5kC2.jpg",
    },
    {
        "title": "Kanguva",
        "release_year": 2024,
        "genre": "Fantasy Action",
        "director": "Siva",
        "synopsis": "A modern-day bounty hunter and an ancient tribal warrior from 1678 share an unresolved mystical connection through centuries of destiny.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8M5kQ1rY8eZ2bK6wT5vL2nZ8tK1.jpg",
    },
    {
        "title": "Captain Miller",
        "release_year": 2024,
        "genre": "Period Action",
        "director": "Arun Matheswaran",
        "synopsis": "A rebellious former colonial soldier turns renegade dacoit to defend his people and their sacred temple loot against British forces.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gK5v32cW2q3NqJ9wK5kX7M5kC3.jpg",
    },
    {
        "title": "Ayalaan",
        "release_year": 2024,
        "genre": "Sci-Fi Comedy",
        "director": "R. Ravikumar",
        "synopsis": "A kind-hearted village youth teams up with an endearing alien visitor to prevent a greedy corporate tycoon from destroying Earth with toxic drilling.",
        "poster_url": "https://image.tmdb.org/t/p/w500/k9vL2nZ8tK1rY4eMw7k6g8M3p5r.jpg",
    },
    {
        "title": "Meiyazhagan",
        "release_year": 2024,
        "genre": "Drama",
        "director": "C. Prem Kumar",
        "synopsis": "A bitter middle-aged man revisits his native town after two decades and encounters an innocent relative whose pure warmth alters his worldview.",
        "poster_url": "https://image.tmdb.org/t/p/w500/eZ2bK6wT5vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Lubber Pandhu",
        "release_year": 2024,
        "genre": "Sports Drama",
        "director": "Tamizharasan Pachamuthu",
        "synopsis": "A spirited rivalry between two gifted gully cricketers of different generations triggers ego clashes, family drama, and community pride.",
        "poster_url": "https://image.tmdb.org/t/p/w500/tK1rY4eMw7k6g8M3p5rQ9vL2nZ8.jpg",
    },
    {
        "title": "Ponniyin Selvan: Part I",
        "release_year": 2022,
        "genre": "Epic Historical",
        "director": "Mani Ratnam",
        "synopsis": "Vandiyathevan embarks on a peril-filled journey across Chola territory to deliver confidential messages, navigating conspiracies against the crown.",
        "poster_url": "https://image.tmdb.org/t/p/w500/943Hk7Fz0i0qN4HkJrXoXwYdE9e.jpg",
    },
    {
        "title": "Ponniyin Selvan: Part II",
        "release_year": 2023,
        "genre": "Epic Historical",
        "director": "Mani Ratnam",
        "synopsis": "Arunmozhi Varman survives turbulent seas as conspiracies culminate into fierce battlefield clashes deciding the fate of the Golden Chola throne.",
        "poster_url": "https://image.tmdb.org/t/p/w500/k22rZq4Z4M8P0eG8q8E6K5tQ1rZ.jpg",
    },
    {
        "title": "Master",
        "release_year": 2021,
        "genre": "Action",
        "director": "Lokesh Kanagaraj",
        "synopsis": "An alcoholic professor is assigned to a juvenile detention center where he crosses paths with a ruthless gangster using inmates for criminal enterprises.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
        "title": "Kaithi",
        "release_year": 2019,
        "genre": "Action Thriller",
        "director": "Lokesh Kanagaraj",
        "synopsis": "A recently paroled convict agrees to drive a truck filled with unconscious police officers through a gauntlet of murderous drug cartels to see his daughter.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6y0T0KzP8s14HkJrXoXwYdE9eR4.jpg",
    },
    {
        "title": "Vikram Vedha",
        "release_year": 2017,
        "genre": "Action Crime",
        "director": "Pushkar-Gayathri",
        "synopsis": "A straight-laced police encounter specialist interrogates a notoriously philosophical gangster who challenges his stark definitions of good and evil.",
        "poster_url": "https://image.tmdb.org/t/p/w500/aE2hK8M5kQ1rY8eZ2bK6wT5vL2n.jpg",
    },
    {
        "title": "Asuran",
        "release_year": 2019,
        "genre": "Action Drama",
        "director": "Vetrimaaran",
        "synopsis": "A modest agrarian father with a hidden violent history goes on the run to save his teenage son after an act of retaliation against wealthy oppressors.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bK6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
    {
        "title": "Pariyerum Perumal",
        "release_year": 2018,
        "genre": "Drama",
        "director": "Mari Selvaraj",
        "synopsis": "A compassionate law student from an oppressed caste struggles against institutional discrimination and cruel social hierarchies with dignity.",
        "poster_url": "https://image.tmdb.org/t/p/w500/cW2q3NqJ9wK5kX7M5kC1aE2hK8M.jpg",
    },
    {
        "title": "Super Deluxe",
        "release_year": 2019,
        "genre": "Dark Comedy Thriller",
        "director": "Thiagarajan Kumararaja",
        "synopsis": "An unfaithful wife, an estranged transgender mother, a corrupt cop, and curious teens face bizarre, life-altering twists of fate on a fateful day.",
        "poster_url": "https://image.tmdb.org/t/p/w500/dE9eR4m1hK5v32cW2q3NqJ9wK5k.jpg",
    },
    {
        "title": "Jai Bhim",
        "release_year": 2021,
        "genre": "Legal Drama",
        "director": "T. J. Gnanavel",
        "synopsis": "A principled human rights lawyer takes on police brutality and systemic prejudice to find a missing tribal laborer falsely implicated in theft.",
        "poster_url": "https://image.tmdb.org/t/p/w500/eG8q8E6K5tQ1rY4eMw7k6g8M3p5.jpg",
    },
    {
        "title": "Soorarai Pottru",
        "release_year": 2020,
        "genre": "Biographical Drama",
        "director": "Sudha Kongara",
        "synopsis": "Nedumaaran Rajangam embarks on a relentless struggle against aviation giants and bureaucracy to launch India's first low-cost airline for the common man.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fT0KzP8s14HkJrXoXwYdE9eR4m1.jpg",
    },
    {
        "title": "Karnan",
        "release_year": 2021,
        "genre": "Action Drama",
        "director": "Mari Selvaraj",
        "synopsis": "A courageous young warrior from an isolated village fights for the fundamental dignity, basic rights, and survival of his marginalized community.",
        "poster_url": "https://image.tmdb.org/t/p/w500/g8M3p5rQ9vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Maanaadu",
        "release_year": 2021,
        "genre": "Sci-Fi Thriller",
        "director": "Venkat Prabhu",
        "synopsis": "A common man and a crooked cop find themselves trapped in a time loop on the day of a high-profile political rally with communal catastrophe looming.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hJ7bX2M5tQ1rY8eZ2bK6wT5vL2n.jpg",
    },
    {
        "title": "Viduthalai Part 1",
        "release_year": 2023,
        "genre": "Crime Drama",
        "director": "Vetrimaaran",
        "synopsis": "A newly recruited idealistic police constable is assigned to capture the elusive leader of a separatist people's militia in rugged mountain forests.",
        "poster_url": "https://image.tmdb.org/t/p/w500/iL2nZ8tK1rY4eMw7k6g8M3p5rQ9.jpg",
    },
    {
        "title": "Jigarthanda DoubleX",
        "release_year": 2023,
        "genre": "Action Western",
        "director": "Karthik Subbaraj",
        "synopsis": "In 1975, a renegade filmmaker and an ambitious Madurai gangster collaborate to shoot a violent western film that evolves into a fight for tribal survival.",
        "poster_url": "https://image.tmdb.org/t/p/w500/jZ8tK1rY4eMw7k6g8M3p5rQ9vL2.jpg",
    },
    {
        "title": "Jigarthanda",
        "release_year": 2014,
        "genre": "Crime Comedy",
        "director": "Karthik Subbaraj",
        "synopsis": "An aspiring director infiltrates the inner circle of a ruthless Madurai mafia boss to make a realistic gangster movie, with chaotic results.",
        "poster_url": "https://image.tmdb.org/t/p/w500/kQ1rY8eZ2bK6wT5vL2nZ8tK1rY4.jpg",
    },
    {
        "title": "Vada Chennai",
        "release_year": 2018,
        "genre": "Crime Epic",
        "director": "Vetrimaaran",
        "synopsis": "An innocent carrom player in north Chennai becomes reluctantly embroiled in the bloody gang feuds and territorial wars spanning three decades.",
        "poster_url": "https://image.tmdb.org/t/p/w500/lM5kQ1rY8eZ2bK6wT5vL2nZ8tK1.jpg",
    },
    {
        "title": "Mahaan",
        "release_year": 2022,
        "genre": "Action Drama",
        "director": "Karthik Subbaraj",
        "synopsis": "A repressed schoolteacher breaks free from strict Gandhian ideals to build a lucrative liquor empire, only to face his estranged, vigilante son.",
        "poster_url": "https://image.tmdb.org/t/p/w500/mK5kX7M5kC1aE2hK8M5kQ1rY8eZ.jpg",
    },
    {
        "title": "Thani Oruvan",
        "release_year": 2015,
        "genre": "Action Thriller",
        "director": "Mohan Raja",
        "synopsis": "A dedicated police officer obsessively stalks an influential scientist whose pharmaceutical crimes destroy innocent lives.",
        "poster_url": "https://image.tmdb.org/t/p/w500/41rY8eZ2bK6wT5vL2nZ8tK1rY4e.jpg",
    },
    {
        "title": "Doctor",
        "release_year": 2021,
        "genre": "Action Comedy",
        "director": "Nelson Dilipkumar",
        "synopsis": "An emotionless military doctor orchestrates an audacious kidnapping scheme to track down and dismantle a human trafficking cartel that abducted his niece.",
        "poster_url": "https://image.tmdb.org/t/p/w500/oE6K5tQ1rY8eZ2bK6wT5vL2nZ8t.jpg",
    },
    {
        "title": "Beast",
        "release_year": 2022,
        "genre": "Action Thriller",
        "director": "Nelson Dilipkumar",
        "synopsis": "A battle-hardened former RAW spy caught inside a hijacked Chennai shopping mall single-handedly takes down terrorists holding hostages.",
        "poster_url": "https://image.tmdb.org/t/p/w500/pT5vL2nZ8tK1rY4eMw7k6g8M3p5.jpg",
    },
    {
        "title": "Mersal",
        "release_year": 2017,
        "genre": "Action Thriller",
        "director": "Atlee",
        "synopsis": "A magician and a 5-rupee doctor identical twin team up to dismantle medical malpractice and avenge their father's tragic death.",
        "poster_url": "https://image.tmdb.org/t/p/w500/qK6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
    {
        "title": "Bigil",
        "release_year": 2019,
        "genre": "Sports Action",
        "director": "Atlee",
        "synopsis": "A former national footballer turned don steps up to coach a women's football team, battling prejudice and underworld rivals to honor his late father.",
        "poster_url": "https://image.tmdb.org/t/p/w500/rY4eMw7k6g8M3p5rQ9vL2nZ8tK1.jpg",
    },
    {
        "title": "Sarkar",
        "release_year": 2018,
        "genre": "Political Action",
        "director": "AR Murugadoss",
        "synopsis": "A globe-trotting corporate CEO returns to India to cast his vote, only to discover it was fraudulently claimed, sparking a political revolution.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sZ2bK6wT5vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Kaththi",
        "release_year": 2014,
        "genre": "Action Drama",
        "director": "AR Murugadoss",
        "synopsis": "A petty criminal discovers his honest doppelganger fighting against a multinational corporate conglomerate trying to seize farmers' lands.",
        "poster_url": "https://image.tmdb.org/t/p/w500/t8eZ2bK6wT5vL2nZ8tK1rY4eMw7.jpg",
    },
    {
        "title": "Thuppakki",
        "release_year": 2012,
        "genre": "Action Thriller",
        "director": "AR Murugadoss",
        "synopsis": "An Indian Army intelligence officer on vacation in Mumbai intercepts a sleeper cell operation, sparking an intellectual battle against terrorist planners.",
        "poster_url": "https://image.tmdb.org/t/p/w500/u1rY8eZ2bK6wT5vL2nZ8tK1rY4e.jpg",
    },
    {
        "title": "Ghilli",
        "release_year": 2004,
        "genre": "Sports Action",
        "director": "Dharani",
        "synopsis": "A state-level kabaddi athlete visits Madurai and accidentally rescues a helpless woman from a feared factional factionist, fleeing to Chennai.",
        "poster_url": "https://image.tmdb.org/t/p/w500/vMw7k6g8M3p5rQ9vL2nZ8tK1rY4.jpg",
    },
    {
        "title": "Sivaji: The Boss",
        "release_year": 2007,
        "genre": "Action Drama",
        "director": "S. Shankar",
        "synopsis": "An NRI software architect returns to India to build free universities and hospitals, fighting systemic black-money syndicates with flair and daring.",
        "poster_url": "https://image.tmdb.org/t/p/w500/w3p5rQ9vL2nZ8tK1rY4eMw7k6g8.jpg",
    },
    {
        "title": "Enthiran",
        "release_year": 2010,
        "genre": "Sci-Fi Action",
        "director": "S. Shankar",
        "synopsis": "A brilliant scientist designs Chitti, an advanced humanoid robot whose freshly installed emotional processors trigger love, jealousy, and chaos.",
        "poster_url": "https://image.tmdb.org/t/p/w500/x5kQ1rY8eZ2bK6wT5vL2nZ8tK1r.jpg",
    },
    {
        "title": "2.0",
        "release_year": 2018,
        "genre": "Sci-Fi Action",
        "director": "S. Shankar",
        "synopsis": "When cell phones across Chennai begin inexplicably swarming through the sky in lethal avian formations, Chitti is reactivated to save humanity.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yK6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
    {
        "title": "Anniyan",
        "release_year": 2005,
        "genre": "Psychological Thriller",
        "director": "S. Shankar",
        "synopsis": "A frustrated consumer lawyer with multiple personality disorder unleashes Anniyan, an ancient garuda-purana vigilante punishing social apathy.",
        "poster_url": "https://image.tmdb.org/t/p/w500/zZ2bK6wT5vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Mudhalvan",
        "release_year": 1999,
        "genre": "Political Thriller",
        "director": "S. Shankar",
        "synopsis": "A bold television journalist is challenged by a corrupt Chief Minister to run the state government for 24 hours, triggering an epochal cleanup.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1K5v32cW2q3NqJ9wK5kX7M5kC1a.jpg",
    },
    {
        "title": "Indian",
        "release_year": 1996,
        "genre": "Vigilante Action",
        "director": "S. Shankar",
        "synopsis": "Senapathy, an aged Indian National Army veteran, uses ancient martial arts to mercilessly execute corrupt government bureaucrats.",
        "poster_url": "https://image.tmdb.org/t/p/w500/2L2nZ8tK1rY4eMw7k6g8M3p5rQ9.jpg",
    },
    {
        "title": "Indian 2",
        "release_year": 2024,
        "genre": "Action Drama",
        "director": "S. Shankar",
        "synopsis": "Senapathy returns from abroad to lead an internet-era crusade against institutional graft alongside disillusioned youth.",
        "poster_url": "https://image.tmdb.org/t/p/w500/3Z8tK1rY4eMw7k6g8M3p5rQ9vL2.jpg",
    },
    {
        "title": "Nayakan",
        "release_year": 1987,
        "genre": "Crime Drama",
        "director": "Mani Ratnam",
        "synopsis": "An orphaned Tamil boy in Mumbai rises to become a benevolent yet ruthless underworld don protecting slum dwellers from police extortion.",
        "poster_url": "https://image.tmdb.org/t/p/w500/4Q1rY8eZ2bK6wT5vL2nZ8tK1rY4.jpg",
    },
    {
        "title": "Baashha",
        "release_year": 1995,
        "genre": "Action",
        "director": "Suresh Krissna",
        "synopsis": "A gentle auto driver in Chennai tries to conceal his colossal past identity as Bombay's most feared mafia emperor to raise his siblings peacefully.",
        "poster_url": "https://image.tmdb.org/t/p/w500/5M5kQ1rY8eZ2bK6wT5vL2nZ8tK1.jpg",
    },
    {
        "title": "Anbe Sivam",
        "release_year": 2003,
        "genre": "Drama Comedy",
        "director": "Sundar C.",
        "synopsis": "Two men of contrasting temperaments — an arrogant ad filmmaker and a scarred socialist philosopher — form an unexpected bond on a shared journey.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6K5kX7M5kC1aE2hK8M5kQ1rY8eZ.jpg",
    },
    {
        "title": "Aayirathil Oruvan",
        "release_year": 2010,
        "genre": "Adventure Action",
        "director": "Selvaraghavan",
        "synopsis": "An archaeological expedition to find a missing scientist stumbles into a concealed, ancient Chola enclave surviving underground in Vietnam.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7Q9wK5kX7M5kC1aE2hK8M5kQ1rY.jpg",
    },
    {
        "title": "Pudhupettai",
        "release_year": 2006,
        "genre": "Gangster Crime",
        "director": "Selvaraghavan",
        "synopsis": "A run-away schoolboy enters the violent politics of north Chennai underworld, clawing his way from henchman to ruthless politician.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8E6K5tQ1rY8eZ2bK6wT5vL2nZ8t.jpg",
    },
    {
        "title": "Vinnaithaandi Varuvaayaa",
        "release_year": 2010,
        "genre": "Romance Drama",
        "director": "Gautham Vasudev Menon",
        "synopsis": "An aspiring Hindu filmmaker falls deeply in love with his orthodox Christian neighbor, undergoing heartbreak and emotional maturity.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9T5vL2nZ8tK1rY4eMw7k6g8M3p5.jpg",
    },
    {
        "title": "Vettaiyaadu Vilaiyaadu",
        "release_year": 2006,
        "genre": "Crime Thriller",
        "director": "Gautham Vasudev Menon",
        "synopsis": "DCP Raghavan travels from Chennai to New York on the trail of two psychopathic medical students turned serial killers.",
        "poster_url": "https://image.tmdb.org/t/p/w500/0K6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
    {
        "title": "Kaakha Kaakha",
        "release_year": 2003,
        "genre": "Action Thriller",
        "director": "Gautham Vasudev Menon",
        "synopsis": "An unyielding police encounter specialist battles a sadistic underworld boss seeking vengeance against the squad.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1Y4eMw7k6g8M3p5rQ9vL2nZ8tK1.jpg",
    },
    {
        "title": "Vaaranam Aayiram",
        "release_year": 2008,
        "genre": "Drama Romance",
        "director": "Gautham Vasudev Menon",
        "synopsis": "An army officer looks back on the life lessons, heartbreak, addiction recovery, and profound love taught to him by his inspiring father.",
        "poster_url": "https://image.tmdb.org/t/p/w500/2Z2bK6wT5vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Mankatha",
        "release_year": 2011,
        "genre": "Action Heist",
        "director": "Venkat Prabhu",
        "synopsis": "A suspended, morally corrupt police commissioner masterminds a 500-crore IPL betting heist with four greedy companions.",
        "poster_url": "https://image.tmdb.org/t/p/w500/38eZ2bK6wT5vL2nZ8tK1rY4eMw7.jpg",
    },
    {
        "title": "Petta",
        "release_year": 2019,
        "genre": "Action Drama",
        "director": "Karthik Subbaraj",
        "synopsis": "A charismatic hostel warden with a lethal gangster history steps in to protect an innocent boy and settle scores with a ruthless politician.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bA41NqYyqU4kK1qY5eX6K5tQ1rY.jpg",
    },
    {
        "title": "Viswasam",
        "release_year": 2019,
        "genre": "Action Drama",
        "director": "Siva",
        "synopsis": "A beloved village chieftain travels to Mumbai to secretly protect his estranged wife and daughter from a vindictive pharmaceutical tycoon.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1hK5v32cW2q3NqJ9wK5kX7M5kC1.jpg",
    },

    # -------------------------------------------------------------
    # PAN-INDIAN (TELUGU, KANNADA, MALAYALAM, HINDI) (61 to 100)
    # -------------------------------------------------------------
    {
        "title": "Kalki 2898 AD",
        "release_year": 2024,
        "genre": "Sci-Fi Action",
        "director": "Nag Ashwin",
        "synopsis": "In a dystopian post-apocalyptic future, immortal warrior Ashwatthama and bounty hunter Bhairava cross paths over the unborn divine savior.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    },
    {
        "title": "Pushpa 2: The Rule",
        "release_year": 2024,
        "genre": "Action Crime",
        "director": "Sukumar",
        "synopsis": "Pushpa Raj expands his red sandalwood smuggling empire into an invincible syndicate while defying ruthless police nemesis Bhanwar Singh Shekhawat.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bA41NqYyqU4kK1qY5eX6K5tQ1rY.jpg",
    },
    {
        "title": "Pushpa: The Rise",
        "release_year": 2021,
        "genre": "Action Crime",
        "director": "Sukumar",
        "synopsis": "A coolie in the Seshachalam forests climbs through the ranks of the red sandalwood underworld through sheer ferocity and unyielding grit.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1hK5v32cW2q3NqJ9wK5kX7M5kC1.jpg",
    },
    {
        "title": "Salaar: Part 1 – Ceasefire",
        "release_year": 2023,
        "genre": "Action Crime",
        "director": "Prashanth Neel",
        "synopsis": "In the sovereign dystopian city-state of Khansaar, a quiet mechanic transforms into a one-man army to help his childhood friend claim the throne.",
        "poster_url": "https://image.tmdb.org/t/p/w500/mK5kX7M5kC1aE2hK8M5kQ1rY8eZ.jpg",
    },
    {
        "title": "RRR",
        "release_year": 2022,
        "genre": "Action Epic",
        "director": "S. S. Rajamouli",
        "synopsis": "A fearless revolutionary and an ambitious British police officer forge an unbreakable brotherhood before discovering each other's secret loyalties.",
        "poster_url": "https://image.tmdb.org/t/p/w500/wE0q5SQ6m9wG8q8E6K5tQ1rY8eZ.jpg",
    },
    {
        "title": "Baahubali: The Beginning",
        "release_year": 2015,
        "genre": "Epic Action",
        "director": "S. S. Rajamouli",
        "synopsis": "Shivudu, an adventurous tribal youth, climbs waterfalls into Mahishmati kingdom and discovers his royal heritage as heir to the throne.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9BAjt85amvlTtLvg4QE3m01J9Te.jpg",
    },
    {
        "title": "Baahubali 2: The Conclusion",
        "release_year": 2017,
        "genre": "Epic Action",
        "director": "S. S. Rajamouli",
        "synopsis": "Amarendra Baahubali chooses honour over crown, falling victim to palace betrayals while his son Mahendra rises to claim justice.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9k22rZq4Z4M8P0eG8q8E6K5tQ1r.jpg",
    },
    {
        "title": "KGF: Chapter 1",
        "release_year": 2018,
        "genre": "Action Period",
        "director": "Prashanth Neel",
        "synopsis": "Rocky arrives in Bombay as an impoverished orphan, rising through mafia ranks before heading to the enslaved Kolar Gold Fields.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bK6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
    {
        "title": "KGF: Chapter 2",
        "release_year": 2022,
        "genre": "Action Period",
        "director": "Prashanth Neel",
        "synopsis": "Rocky establishes an iron grip over KGF as an undisputed ruler, clashing with the ruthless warlord Adheera and the Prime Minister of India.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6A7tQ1rY8eZ2bK6wT5vL2nZ8tK1.jpg",
    },
    {
        "title": "Kantara",
        "release_year": 2022,
        "genre": "Action Mystery",
        "director": "Rishab Shetty",
        "synopsis": "A rebellious Kambala champion finds himself drawn into a conflict between villagers, a principled forest officer, and an ancestral demigod spirit.",
        "poster_url": "https://image.tmdb.org/t/p/w500/dE9eR4m1hK5v32cW2q3NqJ9wK5k.jpg",
    },
    {
        "title": "Devara: Part 1",
        "release_year": 2024,
        "genre": "Action Drama",
        "director": "Koratala Siva",
        "synopsis": "A fearless coastal chieftain vows to put an end to maritime weapon trafficking, instigating a legacy war continued by his mild-mannered son.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7V9N2s8mX4M5kQ1rY8eZ2bK6wT5.jpg",
    },
    {
        "title": "Hanu-Man",
        "release_year": 2024,
        "genre": "Superhero Fantasy",
        "director": "Prasanth Varma",
        "synopsis": "A petty thief in the village of Anjanadri accidentally discovers a solar gem that grants him the boundless superpowers of Lord Hanuman.",
        "poster_url": "https://image.tmdb.org/t/p/w500/w7k6g8M3p5rQ9vL2nZ8tK1rY4eM.jpg",
    },
    {
        "title": "Manjummel Boys",
        "release_year": 2024,
        "genre": "Survival Thriller",
        "director": "Chidambaram",
        "synopsis": "A close-knit group of friends from Kochi launch an impossible, heart-stopping rescue when one of them falls into the bottomless Guna Cave.",
        "poster_url": "https://image.tmdb.org/t/p/w500/jL5cW8mX4M5kQ1rY8eZ2bK6wT5v.jpg",
    },
    {
        "title": "Aavesham",
        "release_year": 2024,
        "genre": "Action Comedy",
        "director": "Jithu Madhavan",
        "synopsis": "Three college students in Bangalore seek the protection of Ranga, an eccentric, white-clad local gangster with a wildly unpredictable persona.",
        "poster_url": "https://image.tmdb.org/t/p/w500/a3K5v32cW2q3NqJ9wK5kX7M5kC2.jpg",
    },
    {
        "title": "Premalu",
        "release_year": 2024,
        "genre": "Romance Comedy",
        "director": "Girish A. D.",
        "synopsis": "A young graduate working at a Hyderabad gate academy falls for a vibrant IT professional, maneuvering hilarious workplace love rivalries.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8M5kQ1rY8eZ2bK6wT5vL2nZ8tK1.jpg",
    },
    {
        "title": "Bramayugam",
        "release_year": 2024,
        "genre": "Horror Mystery",
        "director": "Rahul Sadasivan",
        "synopsis": "A fleeing singer seeks shelter in a decaying 17th-century mansion, discovering that its sinister master commands occult, otherworldly forces.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gK5v32cW2q3NqJ9wK5kX7M5kC3.jpg",
    },
    {
        "title": "The Goat Life (Aadujeevitham)",
        "release_year": 2024,
        "genre": "Survival Drama",
        "director": "Blessy",
        "synopsis": "An Indian migrant worker trapped as a slave herder in the remote deserts of Saudi Arabia undergoes a grueling journey to escape to freedom.",
        "poster_url": "https://image.tmdb.org/t/p/w500/k9vL2nZ8tK1rY4eMw7k6g8M3p5r.jpg",
    },
    {
        "title": "Drishyam",
        "release_year": 2013,
        "genre": "Crime Thriller",
        "director": "Jeethu Joseph",
        "synopsis": "A cinema-loving cable TV operator fabricates an airtight alibi using movie techniques to shield his family from a relentless police investigation.",
        "poster_url": "https://image.tmdb.org/t/p/w500/eZ2bK6wT5vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Drishyam 2",
        "release_year": 2021,
        "genre": "Mystery Thriller",
        "director": "Jeethu Joseph",
        "synopsis": "Six years after the tragedy, Georgekutty faces renewed police scrutiny with forensically unearthed evidence, mounting a new master defense.",
        "poster_url": "https://image.tmdb.org/t/p/w500/tK1rY4eMw7k6g8M3p5rQ9vL2nZ8.jpg",
    },
    {
        "title": "Lucifer",
        "release_year": 2019,
        "genre": "Political Action",
        "director": "Prithviraj Sukumaran",
        "synopsis": "Following the demise of a venerable political patriarch, Stephen Nedumpally emerges from the shadows to protect the state from international cartels.",
        "poster_url": "https://image.tmdb.org/t/p/w500/943Hk7Fz0i0qN4HkJrXoXwYdE9e.jpg",
    },
    {
        "title": "Minnal Murali",
        "release_year": 2021,
        "genre": "Superhero Comedy",
        "director": "Basil Joseph",
        "synopsis": "A tailor struck by lightning gains superhuman agility and strength, locking horns with an outcast who received dark powers from the same bolt.",
        "poster_url": "https://image.tmdb.org/t/p/w500/k22rZq4Z4M8P0eG8q8E6K5tQ1rZ.jpg",
    },
    {
        "title": "Kumbalangi Nights",
        "release_year": 2019,
        "genre": "Drama Comedy",
        "director": "Madhu C. Narayanan",
        "synopsis": "Four estranged brothers sharing a dysfunctional home in the backwaters discover unity, romance, and maturity amidst peculiar village life.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
        "title": "Jawan",
        "release_year": 2023,
        "genre": "Action Thriller",
        "director": "Atlee",
        "synopsis": "A prison warden and his squad of female inmates orchestrate high-profile vigilante heists to force structural reforms against corporate greed.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6y0T0KzP8s14HkJrXoXwYdE9eR4.jpg",
    },
    {
        "title": "Pathaan",
        "release_year": 2023,
        "genre": "Action Spy",
        "director": "Siddharth Anand",
        "synopsis": "An exile Indian RAW field agent embarks on a globe-trotting mission to stop a rogue private mercenary contractor unleashing a biological weapon.",
        "poster_url": "https://image.tmdb.org/t/p/w500/aE2hK8M5kQ1rY8eZ2bK6wT5vL2n.jpg",
    },
    {
        "title": "Animal",
        "release_year": 2023,
        "genre": "Action Drama",
        "director": "Sandeep Reddy Vanga",
        "synopsis": "An obsessively devoted son launches an extreme, ultra-violent crusade across underworld syndicates after an assassination attempt on his father.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bK6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
    {
        "title": "12th Fail",
        "release_year": 2023,
        "genre": "Biographical Drama",
        "director": "Vidhu Vinod Chopra",
        "synopsis": "The poignant true story of Manoj Kumar Sharma, who overcomes extreme poverty, dishonesty, and repeated failures to restart and become an IPS officer.",
        "poster_url": "https://image.tmdb.org/t/p/w500/cW2q3NqJ9wK5kX7M5kC1aE2hK8M.jpg",
    },
    {
        "title": "Dangal",
        "release_year": 2016,
        "genre": "Sports Drama",
        "director": "Nitesh Tiwari",
        "synopsis": "Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to triumph against social stigmas and win Commonwealth gold medals.",
        "poster_url": "https://image.tmdb.org/t/p/w500/dE9eR4m1hK5v32cW2q3NqJ9wK5k.jpg",
    },
    {
        "title": "3 Idiots",
        "release_year": 2009,
        "genre": "Comedy Drama",
        "director": "Rajkumar Hirani",
        "synopsis": "Two engineering friends recount their college days with Rancho, a free-spirited innovator who taught them to chase excellence over success.",
        "poster_url": "https://image.tmdb.org/t/p/w500/eG8q8E6K5tQ1rY4eMw7k6g8M3p5.jpg",
    },
    {
        "title": "Tumbbad",
        "release_year": 2018,
        "genre": "Fantasy Horror",
        "director": "Rahi Anil Barve",
        "synopsis": "A man's boundless greed drives him into the subterranean vaults of a cursed ancestral mansion to extract gold from an ancient demon god.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fT0KzP8s14HkJrXoXwYdE9eR4m1.jpg",
    },
    {
        "title": "Stree",
        "release_year": 2018,
        "genre": "Horror Comedy",
        "director": "Amar Kaushik",
        "synopsis": "In the town of Chanderi, a talented tailor and his companions search for a female spirit that abducts men during annual festive nights.",
        "poster_url": "https://image.tmdb.org/t/p/w500/g8M3p5rQ9vL2nZ8tK1rY4eMw7k6.jpg",
    },
    {
        "title": "Stree 2",
        "release_year": 2024,
        "genre": "Horror Comedy",
        "director": "Amar Kaushik",
        "synopsis": "The town of Chanderi is plagued by a terrifying headless ghost named Sarkata, forcing the gang to unite with Stree to save the women.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hJ7bX2M5tQ1rY8eZ2bK6wT5vL2n.jpg",
    },
    {
        "title": "Sholay",
        "release_year": 1975,
        "genre": "Action Western",
        "director": "Ramesh Sippy",
        "synopsis": "A retired police officer hires two intrepid ex-convicts to bring down Gabbar Singh, a dreaded dacoit who terrorizes Ramgarh.",
        "poster_url": "https://image.tmdb.org/t/p/w500/iL2nZ8tK1rY4eMw7k6g8M3p5rQ9.jpg",
    },
    {
        "title": "Lagaan",
        "release_year": 2001,
        "genre": "Epic Sports Drama",
        "director": "Ashutosh Gowariker",
        "synopsis": "During British rule, villagers in Champaner stake their livelihood on a game of cricket against colonial officers to cancel oppressive taxes.",
        "poster_url": "https://image.tmdb.org/t/p/w500/jZ8tK1rY4eMw7k6g8M3p5rQ9vL2.jpg",
    },
    {
        "title": "Gangs of Wasseypur",
        "release_year": 2012,
        "genre": "Crime Epic",
        "director": "Anurag Kashyap",
        "synopsis": "A multigenerational blood feud erupts between three crime families struggling for dominion over the coal mafia of Dhanbad.",
        "poster_url": "https://image.tmdb.org/t/p/w500/kQ1rY8eZ2bK6wT5vL2nZ8tK1rY4.jpg",
    },
    {
        "title": "Andhadhun",
        "release_year": 2018,
        "genre": "Crime Thriller",
        "director": "Sriram Raghavan",
        "synopsis": "A piano player pretending to be blind inadvertently walks into the murder scene of a retired film actor, triggering a cascade of deception.",
        "poster_url": "https://image.tmdb.org/t/p/w500/lM5kQ1rY8eZ2bK6wT5vL2nZ8tK1.jpg",
    },
    {
        "title": "Toxic: A Fairy Tale for Grown-ups",
        "release_year": 2025,
        "genre": "Action Thriller",
        "director": "Geetu Mohandas",
        "synopsis": "A ruthless cartel kingpin operating in the high-stakes underworld of Goa confronts shifting alliances, revenge, and deep-seated betrayal.",
        "poster_url": "https://image.tmdb.org/t/p/w500/mK5kX7M5kC1aE2hK8M5kQ1rY8eZ.jpg",
    },
    {
        "title": "Spirit",
        "release_year": 2025,
        "genre": "Action Crime",
        "director": "Sandeep Reddy Vanga",
        "synopsis": "A fierce, sincere police officer with an unbending sense of morality wades into a bloody criminal underworld where duty and survival collide.",
        "poster_url": "https://image.tmdb.org/t/p/w500/nQ9wK5kX7M5kC1aE2hK8M5kQ1rY.jpg",
    },
    {
        "title": "Eega",
        "release_year": 2012,
        "genre": "Fantasy Action",
        "director": "S. S. Rajamouli",
        "synopsis": "A slain lover is reincarnated as a housefly and embarks on an ingenious, relentless campaign to torment and kill his wealthy murderer.",
        "poster_url": "https://image.tmdb.org/t/p/w500/oE6K5tQ1rY8eZ2bK6wT5vL2nZ8t.jpg",
    },
    {
        "title": "Magadheera",
        "release_year": 2009,
        "genre": "Fantasy Action",
        "director": "S. S. Rajamouli",
        "synopsis": "A stunt biker discovers memories of his past life as Kala Bhairava, a heroic warrior in 17th-century Rajasthan whose love was torn apart by betrayal.",
        "poster_url": "https://image.tmdb.org/t/p/w500/pT5vL2nZ8tK1rY4eMw7k6g8M3p5.jpg",
    },
    {
        "title": "Kantara: Chapter 1",
        "release_year": 2025,
        "genre": "Mythological Action",
        "director": "Rishab Shetty",
        "synopsis": "The mythical origin story of the Panjurli and Guliga deities during the reign of the Kadambas, where indigenous warriors defend sacred groves.",
        "poster_url": "https://image.tmdb.org/t/p/w500/qK6wT5vL2nZ8tK1rY4eMw7k6g8M.jpg",
    },
]


class Command(BaseCommand):
    help = "Seed 100 famous Tamil and Indian movies into the database"

    def handle(self, *args, **options):
        self.stdout.write("Starting to seed 100 Tamil & Indian movies...")
        created_count = 0
        updated_count = 0

        seen_titles = set()
        cleaned_movies = []
        for m in MOVIES_100:
            if m["title"] not in seen_titles:
                seen_titles.add(m["title"])
                cleaned_movies.append(m)

        for item in cleaned_movies:
            movie, created = Movie.objects.get_or_create(
                title=item["title"],
                defaults={
                    "release_year": item["release_year"],
                    "genre": item["genre"],
                    "director": item["director"],
                    "synopsis": item["synopsis"],
                    "poster_url": item["poster_url"],
                }
            )
            if created:
                created_count += 1
            else:
                movie.release_year = item["release_year"]
                movie.genre = item["genre"]
                movie.director = item["director"]
                movie.synopsis = item["synopsis"]
                if item.get("poster_url"):
                    movie.poster_url = item["poster_url"]
                movie.save()
                updated_count += 1

        total_movies = Movie.objects.count()
        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully seeded {len(cleaned_movies)} movies! "
                f"Created: {created_count}, Updated: {updated_count}. "
                f"Total movies in database: {total_movies}."
            )
        )
